### ISSUE TITLE
Something wrong with bootstrap yaml file rendering

### ISSUE THREAD

**Issue by dtherhtun** [gitops-bridge-dev/gitops-bridge-argocd-bootstrap-terraform#12]
`./bootstrap/addons.yaml`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: system
  source:
    helm:
      values: |
        "account": "{{metadata.annotations.aws_account_id}}"
        "clusterName": "{{metadata.annotations.cluster_name}}"
        "region": "{{metadata.annotations.aws_region}}"
        "repoUrl": "{{metadata.annotations.addons_repo_revision}}"
    path: '{{metadata.annotations.addons_repo_path}}' #chart
    repoURL: '{{metadata.annotations.addons_repo_url}}'
    targetRevision: '{{metadata.annotations.addons_repo_revision}}'
  syncPolicy:
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      limit: 10
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
```
all of the metadata.annotations are successfully created as secret.
